FROM node:18-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Menghasilkan folder dist/ yang berisi file optimasi produksi
RUN npm run build

# Menandakan port preview yang akan digunakan
EXPOSE 3001

# Menjalankan Vite preview server agar bisa diakses
CMD [ "npm", "run", "preview", "--", "--host", "0.0.0.0", "--port", "3001" ]